# Generated by Django 3.1.2 on 2020-10-29 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 29, 13, 16, 4, 869815)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_code_expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 29, 13, 16, 4, 869226)),
        ),
    ]
